import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whackos Trumio Submission</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex flex-col items-center bg-purple-50">
        <h1 className="text-5xl font-bold text-blue-600 mb-4">Welcome to Next.js with Tailwind CSS</h1>
        <p className="text-xl text-gray-700">
          This is a simple webpage styled with Tailwind CSS.
        </p>
        <h2 className="text-2xl font-bold text-purple-700 mt-4">Welcome to My Projects Website</h2>
        <Link href="/project">
          <div className="text-blue-600 cursor-pointer">View Projects</div>
        </Link>
      </main>
    </div>
  );
}
